[[constraint]]
  branch = "master"
  name = "github.com/vsapronov/casee"

[[constraint]]
  branch = "v3"
  name = "github.com/vsapronov/yaml"

[[constraint]]
  name = "gotest.tools"
  version = "2.3.0"

[prune]
  go-tests = true
  unused-packages = true
